{% set name = "supermorecado" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supermorecado-{{ version }}.tar.gz
  sha256: b51664d2eb12326e657a9d80c6849857c42ef3876545515ef988e266e6cc9654

build:
  entry_points:
    - supermorecado = supermorecado.scripts.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit >=3.2,<4
    - pip
  run:
    - python >=3.8
    - morecantile
    - rasterio
    - attrs
    - affine
    - cligj
    - numpy
    - click

test:
  imports:
    - supermorecado
  commands:
    - pip check
    - supermorecado --help
  requires:
    - pip

about:
  summary: Extend the functionality of morecantile with additional commands.
  home: https://github.com/developmentseed/supermorecado
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
