{% set name = "supermorecado" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supermorecado-{{ version }}.tar.gz
  sha256: b3f43e0ea475473da8c9b54af340f2cf6edc0b0abc7c0f1c06ba6d1fe6a75892

build:
  entry_points:
    - supermorecado = supermorecado.scripts.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit >=3.2,<4
    - pip
  run:
    - python >=3.8
    - morecantile
    - rasterio

test:
  imports:
    - supermorecado
  commands:
    - pip check
    - supermorecado --help
  requires:
    - pip

about:
  summary: Extend the functionality of morecantile with additional commands.
  home: https://github.com/developmentseed/supermorecado
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
